### PR TITLE
feat: tooltips first round

### LINKED ISSUE #338: Tooltips v1
All these terms have tooltips but on hover, say 'click more to see about undefined' which feels sloppy and when you click on them, they lead to the solana knowledge base book with no reference to the actual term. 
Adding spreadsheet of tooltip copy here: https://docs.google.com/spreadsheets/d/1XKHy6T7EQoBjlkF1kEOUeIPIhJFfXpEnMdhvXZdbqs8/edit#gid=0

Notes:
There is some linking work still yet to do (once the TdS FAQ info is in the knowledge base) but at least everything has a better definition so I'm moving this to the todo column for @manuel-calavera or @sunnygleason to knock out at some point. 

OK I know @manuel-calavera  will be able to make a tooltip link component for this. The
only slightly tricky part I remember is linking to "book" versus "book-edge" depending
on the deployed stage (see the old code below).

https://github.com/solana-labs/blockexplorer/blob/master/src/v2/Bx2HelpLink.jsx

### PR DESCRIPTION
**Pull request by manuel-calavera**
Fixes #338

### CODE REVIEW

**Comment by sunnygleason** [comment]
@manuel-calavera looks good, thank you!

Since this is documentation-mostly, I'll merge quickly so folks can look
at it through the UI on Edge (or click back to JS if they prefer) 😄 .

@mvines @CriesofCarrots @sbhargava FYI...

**Comment by sunnygleason** [comment]
FYI available http://edge.explorer.solana.com/

**Comment by sbhargava** [comment]
Screen Shot 2019-09-11 at 9 51 10 AM

Click here for more info about: <definition> reads pretty awkward. If anything, 'Click for more info' should be after the definition.

**Comment by sbhargava** [comment]
Moving to done after review. One minor note: Next iteration, we may consider adding after each definition 'Click for more info' to make it clear that you click on the tooltip to travel to the book or faq or documentation around the term. But I hypothesize for now that it is intuitive you can do that and we can wait til we get some data/feedback before making further changes.

**Pull request merged**
