### PR TITLE
fix: commission format on detail page

### LINKED ISSUE #476: Commission on validator list display doesn't match commission on validator detail page
Screen Shot 2019-10-02 at 12 37 52 PM
Screen Shot 2019-10-02 at 12 37 42 PM

### PR DESCRIPTION
**Pull request by manuel-calavera**
Fixes #476

### CODE REVIEW

**Comment by sunnygleason** [comment]
@mvines @CriesofCarrots @chris-remus just checking -- are we actually
exposing the "raw" commission value as a user-facing data type? My
impression was that the int value is a hidden implementation detail, and
the percentage is what users actually see in UIs?

**Comment by CriesofCarrots** [comment]
> @mvines @CriesofCarrots @chris-remus just checking -- are we actually
> exposing the "raw" commission value as a user-facing data type? My
> impression was that the int value is a hidden implementation detail, and
> the percentage is what users actually see in UIs?
> 
> see: https://github.com/solana-labs/networkexplorer/pull/504/files#diff-65cba683a343c5a5c98524ab90564d5fR122

I can see the value of having the raw number available, since that's the input validators use, and they may want to confirm their settings on the network explorer.
But I'll defer to the others on this.

Either way, I think the main thrust of issue #476 was consistency between the validators table and individual validator detail pages, which I don't think this PR resolves...

**Comment by manuel-calavera** [comment]
@CriesofCarrots why do you think so? change I made is for consistency. We show raw value in table and we show raw value on detail page (plus percentage). It is a similar to staked sol field behavior. If you want smth else please let me know.

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots why do you think so? change I made is for consistency. We show raw value in table and we show raw value on detail page (plus percentage). It is a similar to staked sol field behavior. If you want smth else please let me know.

Hmm, I wasn't thinking about it that way. You're right about staked sol.
In that case, fine by me!

**Pull request merged**
