### PR TITLE
Add accounts index link to NavBar

### PR DESCRIPTION
**Pull request by sunnygleason**
Proposal:

* add accounts index link to Nav Bar
* (if approved, we'll need an account icon as well, this is just a placeholder)

image

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
I agree with the need and like the placement.
Are the icons from a common set or custom designs?

**Comment by sunnygleason** [comment]
@CriesofCarrots the other icons are from the designers; I just put in a placeholder from material-ui icons (https://material-ui.com/components/material-icons/)

**Comment by CriesofCarrots** [comment]
@sbhargava @aaronvaughn , best way to acquire a matching icon for Accounts?

**Comment by sunnygleason** [comment]
@CriesofCarrots I was able to fix up the icon to get it pretty close. Merging this proactively since it provides some useful functionality. Feedback always welcome!

**Pull request merged**
