### PR TITLE
RFC/WIP: tds lane computation based on block count/duration

### PR DESCRIPTION
**Pull request by sunnygleason**
Problem:

* the current bikes don't race 😞 

Solution:

* implement the race position function as: `blockBasedPosition + stakeBasedAdjustment` 🚲 
* since it's so hard to test, put in a demo mode for the meantime so folks can check out the mechanics 🐎 

This can probably stay in pending for a while as folks get a chance to view & comment on it, the changes are pretty self-contained.

### CODE REVIEW

**Comment by mvines** [comment]
Neat!   I'm 100% sure that we'll get questions about how the positions are computed, some of which aren't developers.  I'd like to be able to refer them to a write up somewhere, either in README.md or some other markdown file that allows them to understand what's going on.

**Comment by manuel-calavera** [comment]
i know it is not a final code but I still want to make sure that we will not be having this type of calculation on ui components part. It should find it is home on api layer. Ui just renders state.

**Comment by sunnygleason** [comment]
@manuel-calavera all the configuration & TdS-specific functionality
is in the webapp at this point.

My first impression is that I'm not sure it is the best use of time to
push all of this code & config down into the API layer. @mvines, what
do you think we should do based on the life span of this feature set?

**Comment by mvines** [comment]
Hard to say.   TdS *probably* wraps up this year but then unclear if we'd want to repurpose the code for some other initiatives.   Cleanly factored code is always easier to deal with later (be it reuse to remove), but basically I don't think anybody knows.  So your decision will be as good as mine here :)

**Comment by sunnygleason** [comment]
closing in favor of #527

**Pull request closed without merging**
